version: 2
enable-beta-ecosystems: true
updates:
  # Python via uv
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 25
    groups:
      python-packages:
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 25
