[project]
name = "ess-dive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = [
  "setuptools >= 65.0",
]
build-backend = "setuptools.build_meta"
