name: CI

# Configure GHA to run this workflow whenever either:
# (a) a pull request is opened or updated, or
# (b) a commit(s) is pushed into the `main` branch.
on:
  pull_request: { }
  push: { branches: [ main ] }

jobs:
  pr-check:
    name: PR checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          # Note: We added this `version: "latest"` to work around the following bug in this GHA:
          #       https://github.com/astral-sh/setup-uv/issues/489
          version: "latest"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check formatting
        run: uv run ruff format --check -- src/

      - name: Linting
        run: uv run ruff check -- src/

      # Note: This spins up containers running the default services.
      #       This does not include the `ingest` or `test` services,
      #       which aren't part of the default profile.
      - name: Spin up Docker Compose stack in background
        run: docker compose up --detach

      # Note: The `--exit-code-from test` option applies the exit code of the `test` container
      #       to the `docker compose` process, so that the GHA step fails if tests fail.
      #       Reference: https://docs.docker.com/reference/cli/docker/compose/up/
      - name: Spin up `test` container
        run: docker compose up --exit-code-from test test

      # Delete the Python virtual environment created by the container. Otherwise,
      # it will conflict with the one created locally in the next step.
      - name: Delete leftover Python virtual environment
        run: sudo rm -rf ./.venv

      # Run the tests outside of the Docker Compose stack, to ensure they'll pass for developers
      # running them locally (e.g. via `uv run pytest`).
      - name: Run tests locally
        run: uv run pytest -v

      # Note: This spins everything down.
      - name: Spin down Docker Compose stack
        run: docker compose down
