name: CI

on:
  push:
#    branches:
#      - main
  pull_request:

jobs:
  pr-check:
    name: PR checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          # Note: We added this `version: "latest"` to work around the following bug in this GHA:
          #       https://github.com/astral-sh/setup-uv/issues/489
          version: "latest"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check formatting
        run: uv run ruff format --check -- src/

      - name: Linting
        run: uv run ruff check -- src/

      - name: Run tests locally
        run: uv run pytest tests

      - name: Run tests in container environment
        uses: hoverkraft-tech/compose-action@v2.2.0
        env:
          ACTIONS_RUNNER_DEBUG: true
        with:
          compose-file: "docker-compose.yml"
          services: "test"
