name: CI

on:
  push:
#    branches:
#      - main
  pull_request:

jobs:
  pr-check:
    name: PR checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          # Note: We added this `version: "latest"` to work around the following bug in this GHA:
          #       https://github.com/astral-sh/setup-uv/issues/489
          version: "latest"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check formatting
        run: uv run ruff format --check -- src/

      - name: Linting
        run: uv run ruff check -- src/

      - name: Run tests locally
        run: uv run pytest tests

      # Note: This spins up containers running the default services.
      #       This does not include the `ingest` or `test` services,
      #       which aren't part of the default profile.
      - name: Spin up Docker Compose stack in background
        env:
          # Customize MongoDB connection parameters for all containers in the stack.
          MONGO_USERNAME: admin
          MONGO_PASSWORD: root
          MONGO_HOST: mongo
        run: docker compose up --detach

      # Note: The `--exit-code-from test` option applies the exit code of the `test` container
      #       to the `docker compose` process, so that the GHA step fails if tests fail.
      #       Reference: https://docs.docker.com/reference/cli/docker/compose/up/
      - name: Spin up `test` container
        env:
          # Customize MongoDB connection parameters for the `test` container.
          MONGO_USERNAME: admin
          MONGO_PASSWORD: root
          MONGO_HOST: mongo
        run: docker compose up --exit-code-from test test

      # Note: This spins everything down.
      - name: Spin down Docker Compose stack
        run: docker compose down
